version: '3'
services:
  selenium-firefox:
    image: selenium/standalone-firefox
    container_name: selenium-firefox
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

  java-test:
    build: .
    container_name: selenium-java-test
    depends_on:
      - selenium-firefox
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
